In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print("All library imported successfully")

All library imported successfully


In [3]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.zeros ( (3,3 ) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.rand(3, 2)

array([[0.8225068 , 0.0685422 ],
       [0.94028291, 0.02345676],
       [0.82975161, 0.67212217]])

In [11]:
np.random.randn(3, 2)

array([[-1.8267656 , -1.24107018],
       [-1.69810688, -0.03375062],
       [-0.52982396,  0.01699285]])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
print(arr.shape)

(2, 3)


In [15]:
print(arr.ndim)

2


In [16]:
print(arr.size)

6


In [17]:
print(arr.dtype)

int64


In [ ]:
Array operations

In [21]:
a=np.array([1,2,3])

b=np.array([4,5,6])

In [22]:
a+b

array([5, 7, 9])

In [23]:
a*b

array([ 4, 10, 18])

In [24]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
Matrix multiplication

In [25]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
Aggregation

In [27]:
arr=np.array([1,2,3,4])

In [28]:
arr.mean()

np.float64(2.5)

In [29]:
arr.max()

np.int64(4)

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.std()

np.float64(1.118033988749895)

In [ ]:
Indexing and Slicing

In [ ]:
arr=np.array([1,2,3,4,5])

In [32]:
arr[0]

np.int64(1)

In [33]:
arr[1:4]

array([2, 3, 4])

In [34]:
arr[::2]

array([1, 3])

In [ ]:
2D arrays

In [35]:
arr=np.array([[1,2,3],[4,5,6]])

In [36]:
arr[0,1]

np.int64(2)

In [37]:
arr[:,1]

array([2, 5])

In [38]:
arr[1,:2]

array([4, 5])

In [ ]:
Boolean indexing

In [39]:
arr=np.array([1,2,3,4,5])

In [40]:
mask=arr>3

In [41]:
arr[mask]

array([4, 5])

In [ ]:
Reshaping&Combining Arrays

In [45]:
arr=np.arange(6)

In [46]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [ ]:
Stacking

In [48]:
np.vstack((a,b))
np.hstack((a,b))

array([1, 2, 3, 4])

In [ ]:
Broadcasting

In [50]:
a = np.array([1,2,3])
a + 5 

array([6, 7, 8])

In [ ]:
Saving and loading Arrays

In [ ]:
np.save('array.npy',arr)

In [ ]:
loaded_arr=np.load('array.npy')